/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tju_bluetoothlegatt5_JNI_filter */

#ifndef _Included_com_tju_bluetoothlegatt52_JNI_filter
#define _Included_com_tju_bluetoothlegatt52_JNI_filter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tju_bluetoothlegatt5_JNI_filter
 * Method:    DC_filter
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_tju_bluetoothlegatt52_JNI_1filter_DC_1filter
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
