/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tju_bluetoothlegatt5_JNI_fft */

#ifndef _Included_com_tju_bluetoothlegatt52_JNI_fft
#define _Included_com_tju_bluetoothlegatt52_JNI_fft
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tju_bluetoothlegatt5_JNI_fft
 * Method:    fft
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_com_tju_bluetoothlegatt52_JNI_1fft_fft
  (JNIEnv *, jobject, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
